// キャストデータ（フォールバック用）
// 通常はページ表示時に script.js が店舗サイト（host2.jp）から最新データを自動取得し、
// これを上書きして使う。取得に失敗した場合や、動的取得の仕組みごと使えない環境向けの
// 保存データとしてこのファイルを残している。
// 2026-09-18 時点で店舗サイトから取得した内容（X/Instagram/TikTokは登録が無いキャストは空文字）。
// 定期的に更新しておくと、動的取得が失敗したときの表示がより正確になる。
const CASTS = [
  { id: 'naru', name: '椿　鳴', nameRomaji: 'Naru　Tsubaki', sns: { x: 'https://x.com/naru_ggg', instagram: 'https://www.instagram.com/tubakinaru', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/naru/' } },
  { id: 'kanzakirise', name: '神崎　リセ', nameRomaji: 'Rise　Kanzaki', sns: { x: '', instagram: 'https://www.instagram.com/since_yourise', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kanzakirise/' } },
  { id: 'ibuki', name: '後藤　聖輝', nameRomaji: 'Ibuki　Goto', sns: { x: 'https://x.com/ibukipuu_since', instagram: 'https://www.instagram.com/ibukipuu_since', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/ibuki/' } },
  { id: 'kaoru03', name: 'カヲル', nameRomaji: 'Kaoru', sns: { x: 'https://x.com/sinceyou_kaworu', instagram: 'https://www.instagram.com/since_kaworu', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kaoru03/' } },
  { id: 'seri', name: 'セリ', nameRomaji: 'Seri', sns: { x: 'https://x.com/since_seri', instagram: 'https://www.instagram.com/seicham926', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/seri/' } },
  { id: 'yukiya', name: '雪也', nameRomaji: 'Yukiya', sns: { x: 'https://x.com/sinceyouyukiya', instagram: 'https://www.instagram.com/yukiya.1114', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/yukiya/' } },
  { id: 'natsuki02', name: '心　なつき', nameRomaji: 'Natsuki　Kokoro', sns: { x: 'https://x.com/coco_1203_456', instagram: 'https://www.instagram.com/coco_1203_456', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/natsuki02/' } },
  { id: 'reno', name: 'れの', nameRomaji: 'Reno', sns: { x: 'https://x.com/sinceyou_reno', instagram: 'https://www.instagram.com/sinceyou_reno', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/reno/' } },
  { id: 'rikumero1', name: 'リクメロ', nameRomaji: 'Rikumero', sns: { x: 'https://x.com/RIKU_MERO_NO', instagram: 'https://www.instagram.com/new_riku_mero_no1', tiktok: 'https://www.tiktok.com/@riku_mero_no1', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/rikumero1/' } },
  { id: 'kaoru04', name: '愛咲　薫', nameRomaji: 'Kaoru　Aisaki', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kaoru04/' } },
  { id: 'ai', name: '堂本　曖', nameRomaji: 'Ai　Domoto', sns: { x: 'https://x.com/aichan_host', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/ai/' } },
  { id: 'ryo01', name: 'RYO', nameRomaji: 'Ryo', sns: { x: '', instagram: 'https://www.instagram.com/___ryo.1014', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/ryo01/' } },
  { id: 'ayato02', name: '綾翔', nameRomaji: 'Ayato', sns: { x: 'https://x.com/Ayamaaaaaru', instagram: 'https://www.instagram.com/a8t__0', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/ayato02/' } },
  { id: 'asahi', name: 'あさひ', nameRomaji: 'Asahi', sns: { x: 'https://x.com/asahi_24825', instagram: 'https://www.instagram.com/asahi_24825', tiktok: 'https://www.tiktok.com/@82butter', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/asahi/' } },
  { id: 'shugo', name: '酒・GO', nameRomaji: 'Shu　Go', sns: { x: 'https://x.com/nemkurotsuchi', instagram: 'https://www.instagram.com/gogogosyuuu', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/shugo/' } },
  { id: 'mei03', name: '一ノ瀬　命', nameRomaji: 'Mei　Ichinose', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/mei03/' } },
  { id: 'rento01', name: 'れんと', nameRomaji: 'Rento', sns: { x: '', instagram: 'https://www.instagram.com/rent_ktkr', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/rento01/' } },
  { id: 'yuno', name: 'ユノ', nameRomaji: 'Yuno', sns: { x: 'https://x.com/since_youno', instagram: 'https://www.instagram.com/since_youno', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/yuno/' } },
  { id: 'ryoma', name: '龍馬', nameRomaji: 'Ryuma', sns: { x: 'https://x.com/SINCE_youRYUMA', instagram: 'https://www.instagram.com/ryu_361210', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/ryoma/' } },
  { id: 'ren01', name: '一ノ瀬　れん', nameRomaji: 'Ren　Ichinose', sns: { x: 'https://x.com/ichinose_ren1', instagram: 'https://www.instagram.com/since_ren11', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/ren01/' } },
  { id: 'reo01', name: '真白　麗央', nameRomaji: 'Reo　Mashiro', sns: { x: 'https://x.com/sinceyou_reo', instagram: 'https://www.instagram.com/xxsincereo', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/reo01/' } },
  { id: 'chihiro', name: 'ちひろ', nameRomaji: 'Chihiro', sns: { x: 'https://x.com/chihiro9kpq', instagram: 'https://www.instagram.com/_._.chihiro_._', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/chihiro/' } },
  { id: 'takuya', name: '御堂　拓哉', nameRomaji: 'Takuya　Mido', sns: { x: 'https://x.com/sinceyou_takuya', instagram: 'https://www.instagram.com/taku.ya073', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/takuya/' } },
  { id: 'shun03', name: 'しゅん', nameRomaji: 'Shun', sns: { x: '', instagram: 'https://www.instagram.com/since_syun', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/shun03/' } },
  { id: 'kota', name: '皇太', nameRomaji: 'Kota', sns: { x: '', instagram: 'https://www.instagram.com/kota__0703', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kota/' } },
  { id: 'kaisei', name: '海生', nameRomaji: 'Kaisei', sns: { x: 'https://x.com/kaisei0218ay', instagram: 'https://www.instagram.com/kaisei_since', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kaisei/' } },
  { id: 'tsukushi', name: '牧野　つくし', nameRomaji: 'Tsukushi　Makino', sns: { x: 'https://x.com/tukushi_since', instagram: 'https://www.instagram.com/since_tsukushi', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/tsukushi/' } },
  { id: 'aran01', name: '狐爪　アラン', nameRomaji: 'Aran　Kozume', sns: { x: 'https://x.com/shuziccc', instagram: 'https://www.instagram.com/since_pippi', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/aran01/' } },
  { id: 'yu03', name: '天内　悠', nameRomaji: 'Yu　Amanai', sns: { x: 'https://x.com/yuu_since', instagram: 'https://www.instagram.com/yuu_since', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/yu03/' } },
  { id: 'hotaru02', name: '天使　ほたる', nameRomaji: 'Hotaru　Amatsuka', sns: { x: 'https://x.com/since_hota', instagram: 'https://www.instagram.com/samugetan.jp', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/hotaru02/' } },
  { id: 'fuga', name: '楓雅', nameRomaji: 'Fuga', sns: { x: 'https://x.com/since_fu', instagram: 'https://www.instagram.com/fu_ga01', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/fuga/' } },
  { id: 'kyoya01', name: '恭哉', nameRomaji: 'Kyoya', sns: { x: 'https://x.com/kyouya_since', instagram: 'https://www.instagram.com/since.kyouya', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kyoya01/' } },
  { id: 'tete', name: 'テテ', nameRomaji: 'Tete', sns: { x: 'https://x.com/5rJ7pjM16w31222', instagram: 'https://www.instagram.com/euphoria_0804', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/tete/' } },
  { id: 'atora', name: '大森　アトラ', nameRomaji: 'Atora　Omori', sns: { x: 'https://x.com/mgaasahi', instagram: 'https://www.instagram.com/mgautau', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/atora/' } },
  { id: 'kyoka', name: '泉　鏡花', nameRomaji: 'Kyoka　Izumi', sns: { x: 'https://x.com/Abi8yphYNB77175', instagram: 'https://www.instagram.com/_chukatabetai', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kyoka/' } },
  { id: 'hayato01', name: '隼人', nameRomaji: 'Hayato', sns: { x: 'https://x.com/222hayato0', instagram: 'https://www.instagram.com/222hayato0', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/hayato01/' } },
  { id: 'haoto', name: '波響', nameRomaji: 'Haoto', sns: { x: 'https://x.com/haotodesu', instagram: 'https://www.instagram.com/haotodesu2', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/haoto/' } },
  { id: 'hao01', name: '羽桜', nameRomaji: 'Hao', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/hao01/' } },
  { id: 'mei02', name: '芽生', nameRomaji: 'Mei', sns: { x: 'https://x.com/meiy0401', instagram: 'https://www.instagram.com/meiy.0401', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/mei02/' } },
  { id: 'seika', name: '星華', nameRomaji: 'Seika', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/seika/' } },
  { id: 'eto', name: 'えと', nameRomaji: 'Eto', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/eto/' } },
  { id: 'minami01', name: 'みなみ', nameRomaji: 'Minami', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/minami01/' } },
  { id: 'hyuga01', name: 'ひゅうが', nameRomaji: 'Hyuga', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/hyuga01/' } },
  { id: 'kenshin01', name: '犬神', nameRomaji: 'kenshin', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kenshin01/' } },
  { id: 'seren', name: 'セレン', nameRomaji: 'Seren', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/seren/' } },
  { id: 'kei', name: '京', nameRomaji: 'Kei', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/kei/' } },
  { id: 'reiya01', name: '零夜', nameRomaji: 'Reiya', sns: { x: 'https://x.com/nori0073', instagram: 'https://www.instagram.com/reiya0703', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/reiya01/' } },
  { id: 'rana', name: '京　咲成', nameRomaji: 'Rana　Kanadome', sns: { x: 'https://x.com/ranakanadome', instagram: 'https://www.instagram.com/ranakanadome', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/rana/' } },
  { id: 'eito', name: 'エイト', nameRomaji: 'Eito', sns: { x: 'https://x.com/sinceyou_8', instagram: 'https://www.instagram.com/eito_020312', tiktok: 'https://www.tiktok.com/@sinceyou_eito', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/eito/' } },
  { id: 'tsuguto', name: 'つぐと', nameRomaji: 'Tsuguto', sns: { x: 'https://x.com/tsuguto_syg', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/tsuguto/' } },
  { id: 'akito02', name: 'akito', nameRomaji: 'Akito', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/akito02/' } },
  { id: 'takumi00', name: '拓海', nameRomaji: 'Takumi', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/takumi00/' } },
  { id: 'nagi01', name: '凪', nameRomaji: 'Nagi', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/nagi01/' } },
  { id: 'minato05', name: '波風　ミナト', nameRomaji: 'Minato　Namikaze', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/minato05/' } },
  { id: 'rin', name: '島崎　凛', nameRomaji: 'Rin　Shimazaki', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/rin/' } },
  { id: 'nachi', name: '那智', nameRomaji: 'Nachi', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/nachi/' } },
  { id: 'rion01', name: 'リオン', nameRomaji: 'Rion', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/rion01/' } },
  { id: 'takuma', name: '拓真', nameRomaji: 'Takuma', sns: { x: '', instagram: '', tiktok: '', hosuhosu: 'https://www.host2.jp/shop/sinceyou3/takuma/' } },
];
